### ISSUE TITLE
Cordova Plugin Dependencies

### ISSUE THREAD

**Issue by QuasarX** [GameAnalytics/GA-SDK-CORDOVA#2]
C2 and C3 plugins don't have any cordova dependencies.
If you make Android apk Build, GameAnalytics will not work.
This Cordova plugins not included in project.
**cordova-plugin-gameanalytics
cordova-plugin-device**

**for C3 SDK**
https://www.construct.net/make-games/manuals/addon-sdk/reference/specifying-dependencies

**for C2 SDK**
You need to add this value in edittime.js C2 currently supported only one cordova dependencies. Idk maybe you can talk with Ashley about this, for add multi dependencies.
![image](https://user-images.githubusercontent.com/13033837/44794972-4d0c9a00-abb2-11e8-8a12-9cf69c1bdaab.png)

This will add in config file this part

`<plugin name="cordova-plugin-gameanalytics" />`

**Comment by the1schwartz** [comment]
I have updated the plugin to include the cordova dependencies now
