### ISSUE TITLE
GameAnalytics - not work on mobile

### ISSUE THREAD

**Issue by QuasarX** [GameAnalytics/GA-SDK-CORDOVA#5]
I was test latest Construct 2 GA plugin. It works on preview but not work on mobile. I tested on android device.

**GameEngine:** Construct 2 r268
**GameAnalytics plugin:** 2.2.0
**Cordova CLI:** v9.0.0 

Construct 2 Project File
[GATest.zip](https://github.com/GameAnalytics/GA-SDK-CORDOVA/files/3292739/GATest.zip)

Cordova Export
[GATest-CordovaExport.zip](https://github.com/GameAnalytics/GA-SDK-CORDOVA/files/3292740/GATest-CordovaExport.zip)

**Screenshot - Eventsheet**
![3](https://user-images.githubusercontent.com/13033837/59547327-e3ddf380-8f45-11e9-9337-752c4d974a8f.PNG)

### **GameAnalytics Properties:** **"Enable info log" : FALSE**

**Construct 2 : Preview Project - Chrome (Works fine)**

![GATest-2](https://user-images.githubusercontent.com/13033837/59547253-9745e880-8f44-11e9-9645-59c702aaf86f.PNG)

**Android Device : Chrome Inspector**
**"Enable info log" : FALSE** but it is shows console logs.
![GATest-1](https://user-images.githubusercontent.com/13033837/59547266-c197a600-8f44-11e9-8817-dd18ecbe2436.PNG)

**GameAnalytics Dashboard**
![GATest-3](https://user-images.githubusercontent.com/13033837/59547271-daa05700-8f44-11e9-9597-82df433c9bd2.PNG)

### **GameAnalytics Properties:** **"Enable info log" : TRUE**

**Construct 2 : Preview Project - Chrome (Works fine)**
![test2](https://user-images.githubusercontent.com/13033837/59547278-fd327000-8f44-11e9-8c92-d12042616975.PNG)

**Android Device : Chrome Inspector**
**"Enable info log" : TRUE** but it is shows **same** console logs.
![GATest-1](https://user-images.githubusercontent.com/13033837/59547266-c197a600-8f44-11e9-8817-dd18ecbe2436.PNG)

**Comment by QuasarX** [comment]
I didn't test with **IOS** I hope you will test with **IOS** too

**Comment by the1schwartz** [comment]
I have tested both for android and ios and it seems to work fine. To see the logs though I had enable them in Construct using your provided Construct project and then export to Cordova again and build again for android and ios.

**Comment by QuasarX** [comment]
I tried again.
1.) Reinstall GameAnalytics plugin v2.2.0
2.) Disable all logs via GameAnalytics plugin properties
3.) Export and build apk with Cordova CLI 9.0.0

**ANDROID RESULT**
Still same problem. And I can't get value from "GA CommandCenter". Function runs but It doesn't return value. I can't see "HelloWorld" text on my mobile screen.
![image](https://user-images.githubusercontent.com/13033837/59684709-3e47b000-91e3-11e9-9187-02df9e06a8c5.png)

**PC RESULT**
But on PC preview it is return me "HelloWorld" and I don't see other logs.
![image](https://user-images.githubusercontent.com/13033837/59684812-75b65c80-91e3-11e9-90de-1e7f8cb9c78d.png)

What I'm missing :/

And please, can you share your exported project and debug apk file. I want test it too.
My apk : 
[Test.zip](https://github.com/GameAnalytics/GA-SDK-CORDOVA/files/3301620/Test.zip)

**Comment by the1schwartz** [comment]
Ah I see what you mean now. It looks like you need a callback functions for getting return values when used in a cordova export project. I have updated the SDK now and documentation on how to use [it](https://gameanalytics.com/docs/item/construct-sdk#configs). Let me know if it is still not working for you.

**Comment by QuasarX** [comment]
Installed GA v2.2.2 plugin for Construct 2
I'm sorry I can't get it work. I tried so many things. I can get only 0 or 1 value not "HelloWorld"

Also

1.) You should show what function name for more readable event sheet codes.
![image](https://user-images.githubusercontent.com/13033837/59799163-77b81280-92ec-11e9-804e-793509f673dc.png)

2.) Info logs not work on **Android**. I used this enabled.
![image](https://user-images.githubusercontent.com/13033837/59799262-a7671a80-92ec-11e9-9a79-86eb40d27ab5.png)

This console logs not really GA info logs.
![image](https://user-images.githubusercontent.com/13033837/59799339-d3829b80-92ec-11e9-9eca-68a07c5e26e3.png)

3.) Can you share any example project using CommandCenter?

**Comment by the1schwartz** [comment]
Here is the test project I used to test with: https://drive.google.com/file/d/16HOtzh9H-uTQf7ysl4zpzzVNFBuZ9Ddv/view?usp=sharing

**Comment by the1schwartz** [comment]
Info log should fine I have just tested on Android using the test project provided

**Comment by the1schwartz** [comment]
The function name parameter on the "Is CC ready" condition doesn't seem to be able to show it on the event sheet you need to edit the condition to show it.

**Comment by QuasarX** [comment]
Thanks. I finally got it how it works. but still I don't see info logs in android build. Please watch this video you can see what different in console logs.

https://streamable.com/63rjn

**Comment by the1schwartz** [comment]
The underlying native Android library only logs to LogCat which you should be able to see if you install Android Studio: 
![Screenshot 2019-06-20 at 13 38 09](https://user-images.githubusercontent.com/10114102/59846670-c606f900-9360-11e9-96cd-4c6fe56e4595.png)

**Comment by QuasarX** [comment]
Okay.

Thanks for everything.

I found way to show like this in event sheet. This more readable now. You can update GA plugin like this.
I edit line 59 in **edittime.js** => `"Is CC ready? <b>{0}</b>"`

![image](https://user-images.githubusercontent.com/13033837/59847348-eb990000-936a-11e9-969a-ca86ad377151.png)

![image](https://user-images.githubusercontent.com/13033837/59847386-01a6c080-936b-11e9-986d-bddfbc673ba0.png)

**Comment by the1schwartz** [comment]
Ok great thanks. I will update the plugin now :)
