### ISSUE TITLE
Warning from Google about play-services-tasks

### ISSUE THREAD

**Issue by undergroundcreative** [GameAnalytics/GA-SDK-CORDOVA#9]
Hi there,

When trying to upload an APK to the Google Play store I'm getting the following warning message:

---

The developer of play-services-tasks (com.google.android.gms:play-services-tasks) has reported critical issues with version 18.0.0. Consider upgrading before publishing a new release.

Here's what the SDK developer told us:

play-services-tasks v18.0.0 has known issues that can lead to runtime NPEs (NullPointerException) when handling Task<Void> results in Kotlin code. We strongly recommend that you avoid using this version. This also impacts the SDKs listed in the December 9, 2021 release, because they all depend on play-services-tasks. A fix for this issue is included in play-services-tasks v18.0.1. See https://developers.google.com/android/guides/releases#december_16_2021

---

I'm pretty certain that it's the Game Analytics plugin that is causing the message because if I remove the plugin, the warning disappears.

I'm running plugin version 4.2.5 and I'm using Ionic Appflow to build the APK.

I'd be really grateful if you could suggest a solution or update the plugin with a fix.

Many thanks!

**Comment by the1schwartz** [comment]
I have updated com.google.android.gms:play-services-appset from 16.0.1 to 16.0.2 which is the only dependency the plugin has besides the gameanalytics sdk itself. I hope this will solve the issue. Let me know if it fixes the issue so I can close this one.

**Comment by undergroundcreative** [comment]
Brilliant, that seems to have got rid of the warning message. Thanks for fixing it so promptly, much appreciated!
